---
title: 'GO enrichment analysis of DE miRNA targets'
output: 
  html_document:
  toc: TRUE
toc_float: TRUE
author: 
  - "Ryan Corbett"
  - "Updated by Bicna Song"
date: "2025"
---

This script performs gene ontology (GO) enrichment analysis on DE miRNA predicted targets

Load packages

```{r load-packages}
library(tidyverse)
library(ggplot2)
library(org.Mm.eg.db)
library(topGO)
library(AnnotationDbi)
library(future.apply)
```

Set directory paths

```{r dir-paths}
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))

data_dir <- file.path(root_dir, "data")
analysis_dir <- file.path(root_dir, "analyses", "murine-mirna-go-enrichment")
results_dir <- file.path(analysis_dir, "results")
plot_dir <- file.path(analysis_dir, "plots")

set.seed(2025)
```

Set file paths

```{r file-paths}
de_mirna_file <- file.path(root_dir, "analyses", "murine-mirna-clustering", "results", "mouse_sig_DE_miRNA_list.csv")

miranda_output_file <- file.path(root_dir, "analyses", "murine-novel-mirna-target-prediction", "results", "mouse_miranda_output_parsed_anno.csv")
```

Load DE miRNAs and miRanda output

```{r wrangle-data}
de_mirna_df <- read_csv(de_mirna_file)
top_de_mirnas <- de_mirna_df$mirna_id

miranda_output_df <- read_csv(miranda_output_file) %>%
  filter(Max_Score >= 145, Max_Energy <= -20)
```

```{r mirna-target-counts}
mirna_target_counts <- miranda_output_df %>%
  filter(!is.na(GeneSymbol)) %>%
  distinct(Seq1, GeneSymbol) %>%
  count(Seq1, name = "Num_Target_Genes") %>%
  arrange(desc(Num_Target_Genes))

# View the top results
head(mirna_target_counts, 10)
```

Loop through DE miRNA, extract targets, and perform GO enrichment analyses

```{r get-all-genes}
# create empty lists
de_mirna_target_go_list <- list()

# get list of all genes to use as background for enrichment
all_entrez_ids <- keys(org.Mm.eg.db, keytype = "ENTREZID")

# Map Entrez IDs to Gene Symbols
all_genes <- select(org.Mm.eg.db, keys = all_entrez_ids, 
                    columns = "SYMBOL", keytype = "ENTREZID")
```

```{r run-go}
# Enable parallel processing
plan(multicore, workers = parallel::detectCores() - 1)

# Define function to perform GO enrichment for a single miRNA
run_go_for_mirna <- function(de_mirna) {
  targets <- miranda_output_df %>%
    filter(Seq1 == de_mirna) %>%
    distinct(GeneSymbol) %>%
    pull(GeneSymbol)
  
  if (length(targets) < 20) return(NULL)
  
  target_gene_df <- all_genes %>%
    mutate(target_gene = if_else(SYMBOL %in% targets, 1, 0))
  
  target_genes <- target_gene_df$target_gene
  names(target_genes) <- target_gene_df$SYMBOL
  
  suppressMessages({
    GO_data <- new("topGOdata", ontology = "BP", allGenes = target_genes,
                   geneSel = function(x) x == 1,
                   annot = annFUN.org, mapping = "org.Mm.eg.db", ID = "symbol")
    
    result <- runTest(GO_data, algorithm = "classic", statistic = "fisher")
    go_table <- GenTable(GO_data, classicFisher = result,
                         topNodes = length(usedGO(GO_data)), numChar = 100000)
  })
  
  go_table <- go_table %>%
    mutate(fdr = p.adjust(classicFisher, method = "BH")) %>%
    filter(fdr < 0.05)
  
  if (nrow(go_table) == 0) return(NULL)
  
  # Add gene lists per term
  genes_per_term_df <- enframe(genesInTerm(GO_data), name = "GO.ID", value = "Genes") %>%
    mutate(Genes = sapply(Genes, paste, collapse = ", "))
  
  go_table <- left_join(go_table, genes_per_term_df, by = "GO.ID")
  
  write_tsv(go_table, file.path(results_dir, glue::glue("{de_mirna}-target-go-enrichment.tsv")))
  
  return(go_table)
}

# Run GO enrichment in parallel
de_mirna_target_go_list <- future_lapply(top_de_mirnas, run_go_for_mirna)
```

Print session info

```{r session-info}
sessionInfo()
```


