---
title: 'GO Enrichment Analysis of DE miRNA Targets'
output: 
  html_document:
  toc: TRUE
toc_float: TRUE
author: Ryan Corbett, Bicna Song
date: "`r Sys.Date()`"
---

### Overview
Perform GO enrichment (Biological Process, BP) on differentially expressed (DE) miRNA target genes across histology-specific contrasts.

### Load Required Packages

```{r load-packages, message=FALSE, warning=FALSE}
library(tidyverse)
library(glue)
library(topGO)
library(org.Hs.eg.db)
library(AnnotationDbi)
library(future.apply)
```

### Set directory paths

```{r dir paths}
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))
data_dir <- file.path(root_dir, "data")
analysis_dir <- file.path(root_dir, "analyses", "human-mirna-go-enrichment")
results_dir <- file.path(analysis_dir, "results")
plot_dir <- file.path(analysis_dir, "plots")

set.seed(2025)

# Histologies and controls
histologies <- c("DIPG or DMG", "EPN", "LGG", "MB")
```

### GO enrichment analysis function

```{r}
go_enrichment <- function(mirna, df, hist){

  message("     – GO for ", mirna)
      targets <- df %>%
        filter(miRNA == mirna) %>%
        distinct(target_gene_id) %>%
        pull(target_gene_id)
      
      # Only proceed if at least 20 targets
      if (length(targets) >= 20) {
        
        # Binary vector for topGO
        target_genes <- as.integer(symbol_set %in% targets)
        names(target_genes) <- symbol_set
        
        system.time(
        GO_data <- new("topGOdata",
                       ontology  = "BP",
                       allGenes  = target_genes,
                       geneSel   = function(x) x == 1,
                       annot     = annFUN.org,
                       mapping   = "org.Hs.eg.db",
                       ID        = "symbol",
                       nodeSize  = 10)
        )
        
        # Fisher test + table
        result <- runTest(GO_data, algorithm="classic", statistic="fisher")
        go_tab <- GenTable(GO_data, classicFisher = result,
                           topNodes = 500,
                           numChar  = 100000) %>%
          mutate(fdr = p.adjust(as.numeric(classicFisher), method="BH")) %>%
          filter(fdr < 0.05)
        
        # add genes lists to enriched GO term df
        genes_per_term <- genesInTerm(GO_data)
        
        genes_per_term_df <- enframe(genes_per_term, name = "GO.ID", value = "Genes") %>%
        mutate(Genes = sapply(Genes, function(x) paste(x, collapse = ", ")))
        
        go_tab_add_genes <- go_tab %>%
          left_join(genes_per_term_df)
        
        if (nrow(go_tab_add_genes) > 0) {
          out_file <- glue("{mirna}-{hist}-shared-GO-BP_all.tsv")
          write_tsv(go_tab_add_genes, file.path(results_dir, out_file))
          message("         ✓ Wrote ", nrow(go_tab_add_genes), " terms to ", out_file)
        } else {
          message("         ✗ No significant GO terms for ", mirna)
        }
        
      } else {
        message("         ✗ Only ", length(targets),
                " targets; skipping ", mirna)
      }
      
}
```

### GO Enrichment per Histology and Contrast

```{r go-enrichment, message=TRUE, warning=TRUE}
plan(multisession)

mirna_target_list    <- list()
mirna_target_go_list <- list()

# Precompute background once
all_entrez_ids <- keys(org.Hs.eg.db, keytype = "ENTREZID")
all_genes      <- select(org.Hs.eg.db,
                         keys    = all_entrez_ids,
                         columns = "SYMBOL",
                         keytype = "ENTREZID")

go_annotated_genes <- AnnotationDbi::select(org.Hs.eg.db,
                                            keys    = keys(org.Hs.eg.db, keytype = "GO"),
                                            columns = "SYMBOL",
                                            keytype = "GO") %>%
  dplyr::filter(!is.na(SYMBOL)) %>%
  dplyr::distinct(SYMBOL) %>%
  dplyr::pull(SYMBOL)

# Use this to filter your gene universe
symbol_set <- intersect(all_genes$SYMBOL, go_annotated_genes)

for (hist in histologies) {
  message("▶ Histology: ", hist)
  
  # Determine contrasts
  contrasts <- if (hist %in% c("LGG")) {
    "healthyNormal"
  } else {
    c("healthyNormal", "paired")
  }
  
  # Read DE miRNA lists per contrast
  de_lists <- list()
  for (ctr in contrasts) {
    fname <- if (ctr == "paired") {
    glue("known-mirna-target-gene-differential-expr-{hist}-paired.tsv")
    } else {
      glue("known-mirna-target-gene-differential-expr-{hist}-healthyNormal.tsv")
    }
    path <- file.path(results_dir, fname)
    if (!file.exists(path)) {
      message("   ✗ Missing file: ", fname)
      next
    }
    df <- read_tsv(path, col_types = cols())
    de_lists[[ctr]] <- df %>%
      filter(str_detect(miRNA, "^hsa")) %>%
      distinct(miRNA) %>%
      pull(miRNA)
    message("   • ", ctr, ": ", length(de_lists[[ctr]]), " miRNAs")
  }
  
  # Find miRNAs DE in at least one contrast
  total_de <- unique(unlist(de_lists))
  message("   → DE miRNAs: ", length(total_de))
  if (length(total_de) == 0) next
  
  # run GO enrichment on all shared DE miRNA targets
  future_lapply(total_de, 
                function(x) go_enrichment(x, df, hist))
  
}
```

### Session Info

```{r session-info}
sessionInfo()
```


