---
title: "Convert Novel miRNA Table to FASTA Format"
output: 
  html_document:
    toc: true
    toc_float: true
author: "Bicna Song"
date: "2025-06-30"
---

Setup

```{r setup, message=FALSE, warning=FALSE}
library(readr)
library(dplyr)
library(Biostrings)
```

Directory and File Paths

```{r paths}
root_dir     <- rprojroot::find_root(rprojroot::has_dir(".git"))
data_dir     <- file.path(root_dir, "data")
analysis_dir <- file.path(root_dir, "analyses", "human-novel-mirna-target-prediction")
results_dir  <- file.path(analysis_dir, "results")
output_fasta <- file.path(results_dir, "combined_all_novel_mirna.fa")

batch1_file  <- file.path(root_dir, "analyses", "human-mirna-expression", "results", "30-931106737-all_novel_miRNA_merged_id.tsv")
batch2_file  <- file.path(root_dir, "analyses", "human-mirna-expression", "results", "30-1075661268-all_novel_miRNA_merged_id.tsv")
```

Read and Merge Batches

```{r merge-batches}
# Read both batch tables
batch1 <- read_tsv(batch1_file, col_types = cols())
batch2 <- read_tsv(batch2_file, col_types = cols())

# Stack rows and keep the first occurrence for each merge_id
mirna_df <- bind_rows(batch1, batch2) %>%
  distinct(merged_id, .keep_all = TRUE) %>%
  select(
    merged_id,
    mature_seq,
    star_seq,
    precursor_seq,
    precursor_coordinate
  )

# Inspect merged result
head(mirna_df)
```

Write Merged Table to TSV

```{r write-tsv}
# Save the combined data frame as TSV
write_tsv(
  mirna_df,
  file = file.path(results_dir, "combined_all_novel_mirna.tsv"),
  col_names = FALSE
)
```  

Convert to FASTA format using mature miRNA sequence

```{r}
mature_mirna <- RNAStringSet(mirna_df$mature_seq)
names(mature_mirna) <- mirna_df$merged_id
```

Write FASTA output

```{r}
writeXStringSet(mature_mirna, filepath = output_fasta)
```


