---
title: "Annotate miRanda Output with Gene ID and Gene Symbol"
output:
  html_document:
    toc: true
    toc_float: true
author: "Bicna Song"
date: "2025-04-16"
---

Load packages

```{r load-packages}
library(readr)
library(dplyr)
library(rtracklayer)
```

Set directory paths

```{r dir paths}
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))

data_dir <- file.path(root_dir, "data")
analysis_dir <- file.path(root_dir, "analyses", "human-novel-mirna-target-prediction")
input_dir <- file.path(analysis_dir, "input")
results_dir <- file.path(analysis_dir, "results")
```

Set file paths 

```{r file paths}
de_mirna_file <- file.path(root_dir, "analyses",
                           "human-mirna-differential-expression",
                           "results",
                           "mirna-differential-expr-deseq2-dipg-dmg-versus-normal.tsv")

fasta_path <- file.path(results_dir, "all_novel_miRNA_mature.fa")
output_path <- file.path(results_dir, "novel_de_miRNAs_mature.fa")
```

```{r file paths}
miranda_file <- file.path(results_dir, "miranda_output_parsed.csv")
gtf_file <- file.path(data_dir, "gencode.v39.primary_assembly.annotation.gtf.gz")
output_file <- file.path(results_dir, "miranda_output_parsed_anno.csv")
```

```{r read miranda}
miranda <- read_csv(miranda_file)
```

```{r read gtf}
gtf <- import(gtf_file)
transcript_anno <- gtf[gtf$type == "transcript"]

transcript_df <- as.data.frame(mcols(transcript_anno)) %>%
  select(transcript_id, gene_id, gene_name) %>%
  mutate(transcript_id_clean = sub("\\.\\d+$", "", transcript_id),
         gene_id_clean = sub("\\.\\d+$", "", gene_id)) %>%
  distinct(transcript_id_clean, gene_id_clean, gene_name)
```

```{r join annotations}
miranda_annotated <- miranda %>%
  left_join(transcript_df, by = c("Seq2" = "transcript_id_clean"))

colnames(miranda_annotated)[8] <- "GeneID"
colnames(miranda_annotated)[9] <- "GeneSymbol"
```

```{r write output}
write_csv(miranda_annotated, output_file)
```

```{r session info}
sessionInfo()