---
title: 'GO enrichment analysis of DE miRNA targets'
output: 
  html_document:
  toc: TRUE
toc_float: TRUE
author: Ryan Corbett
date: "2025"
---

This script performs gene ontology (GO) enrichment analysis on DE miRNA predicted targets

Load packages

```{r load packages}
library(tidyverse)
library(ggplot2)

library(topGO)
library(org.Hs.eg.db)  
library(AnnotationDbi)
```

Set directory paths

```{r dir paths}
root_dir <- rprojroot::find_root(rprojroot::has_dir(".git"))

data_dir <- file.path(root_dir, "data")
analysis_dir <- file.path(root_dir, "analyses", "human-mirna-rna-interactions")
results_dir <- file.path(analysis_dir, "results")
plot_dir <- file.path(analysis_dir, "plots")
```

Set file paths 

```{r file paths}
de_mirna_file <- file.path(root_dir, "analyses",
                           "human-mirna-differential-expression",
                           "results",
                           "mirna-differential-expr-deseq2-dipg-dmg-versus-normal.tsv")

azenta_targets_file <- file.path(data_dir,
                          "miRNA_Target_anno.csv")

mirTarBase_targets_file <- file.path(results_dir,
                                     "human-mirna-target-predictions-miRTarBase.tsv.gz")
```

Wrangle data

```{r wrangle data}
de_mirna_df <- read_tsv(de_mirna_file)

azenta_targets_df <- read_csv(azenta_targets_file)

mirTarBase_targets_df <- read_tsv(mirTarBase_targets_file)
```

Pull DE miRNAs, separating known and novel

```{r get miRNAs}
known_de_mirnas <- de_mirna_df %>%
  dplyr::filter(grepl("hsa", mirna_id),
                padj < 0.05) %>%
  pull(mirna_id)

novel_de_mirnas <- de_mirna_df %>%
  dplyr::filter(!grepl("hsa", mirna_id),
                padj < 0.05) %>%
  pull(mirna_id)
```

Run GO enrichment for known DE miRNA targets

```{r known target GO}
# create empty lists
known_mirna_target_list <- list()
known_mirna_target_go_list <- list()

# get list of all genes to use as background for enrichment
all_entrez_ids <- keys(org.Hs.eg.db, keytype = "ENTREZID")

# Map Entrez IDs to Gene Symbols
all_genes <- select(org.Hs.eg.db, keys = all_entrez_ids, 
                    columns = "SYMBOL", keytype = "ENTREZID")

for (known_mirna in known_de_mirnas){
  
  # pull target genes from miRTarBase df
  known_mirna_target_list[[known_mirna]] <- mirTarBase_targets_df %>%
    dplyr::filter(miRNA == known_mirna) %>%
    distinct(`Target Gene`) %>%
    pull(`Target Gene`)
  
  if (length(known_mirna_target_list[[known_mirna]] >= 20)){

    # define all genes as target (1) or not target (0) for enrichment
    target_gene_df <- all_genes %>%
    dplyr::mutate(target_gene = case_when(
      SYMBOL %in% known_mirna_target_list[[known_mirna]] ~ 1,
      TRUE ~ 0
    ))
  
    target_genes <- target_gene_df$target_gene
    names(target_genes) <- target_gene_df$SYMBOL
  
    # Create topGO object, using biological process (BP) ontology terms
    GO_data <- new("topGOdata", ontology = "BP", allGenes = target_genes, 
                                                     geneSel = function(x) x == 1, 
                                                     annot = annFUN.org, mapping = "org.Hs.eg.db", ID = "symbol")
    
    # Run Fisher test
    result <- runTest(GO_data, algorithm = "classic", statistic = "fisher")
    
    # write resutls to go analysis list
   known_mirna_target_go_list[[known_mirna]] <- GenTable(GO_data, classicFisher = result, topNodes = length(usedGO(GO_data)),
                                                         numChar = 100000)
   
   # filter for signficant results
   known_mirna_target_go_list[[known_mirna]] <- known_mirna_target_go_list[[known_mirna]] %>%
     dplyr::mutate(fdr = p.adjust(classicFisher, method = "BH")) %>%
     dplyr::filter(fdr < 0.05)
   
   if (nrow(known_mirna_target_go_list[[known_mirna]]) > 0){
   
     write_tsv(known_mirna_target_go_list[[known_mirna]],
               file.path(results_dir,
                         glue::glue("{known_mirna}-target-go-enrichment.tsv")))
     
   }
   
  }
  
}
```

Run GO enrichment for novel DE miRNA targets

```{r novel target GO}
novel_mirna_target_list <- list()
novel_mirna_target_go_list <- list()

all_entrez_ids <- keys(org.Hs.eg.db, keytype = "ENTREZID")

# Map Entrez IDs to Gene Symbols
all_genes <- select(org.Hs.eg.db, keys = all_entrez_ids, 
                    columns = "SYMBOL", keytype = "ENTREZID")

for (novel_mirna in novel_de_mirnas){
  
  # use azenta predicted targets, since novel miRNAs are not in miRTarBase
  novel_mirna_target_list[[novel_mirna]] <- azenta_targets_df %>%
    dplyr::filter(Seq1 == novel_mirna) %>%
    distinct(GeneSymbol) %>%
    pull(GeneSymbol)
  
  if (length(novel_mirna_target_list[[novel_mirna]] >= 20)){

    target_gene_df <- all_genes %>%
    dplyr::mutate(target_gene = case_when(
      SYMBOL %in% novel_mirna_target_list[[novel_mirna]] ~ 1,
      TRUE ~ 0
    ))
  
    target_genes <- target_gene_df$target_gene
    names(target_genes) <- target_gene_df$SYMBOL
  
    # Create topGO object
    GO_data <- new("topGOdata", ontology = "BP", allGenes = target_genes,
                                                     geneSel = function(x) x == 1,
                                                     annot = annFUN.org, mapping = "org.Hs.eg.db", ID = "symbol")
  
    # Run Fisher test
    result <- runTest(GO_data, algorithm = "classic", statistic = "fisher")
  
    # View results
   novel_mirna_target_go_list[[novel_mirna]] <- GenTable(GO_data, classicFisher = result, topNodes = length(usedGO(GO_data)),
                                                         numChar = 100000)
  
   novel_mirna_target_go_list[[novel_mirna]] <- novel_mirna_target_go_list[[novel_mirna]] %>%
     dplyr::mutate(fdr = p.adjust(classicFisher, method = "BH")) %>%
     dplyr::filter(fdr < 0.05)
   
   if (nrow(novel_mirna_target_go_list[[novel_mirna]]) > 0){
  
     write_tsv(novel_mirna_target_go_list[[novel_mirna]],
               file.path(results_dir,
                         glue::glue("{novel_mirna}-target-go-enrichment.tsv")))
     
   }
   
  }
  
}
```

print session info

```{r session info}
sessionInfo()
```

